# Generated by Django 5.1.6 on 2025-02-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_usermodel_email_alter_usermodel_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
