# Generated by Django 5.1.6 on 2025-02-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_usermodel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='userId',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
