# Generated by Django 5.1.6 on 2025-02-18 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_todo_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
