# Generated by Django 5.1.6 on 2025-02-18 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_todo_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='userId',
        ),
    ]
