# Generated by Django 5.1.7 on 2025-03-30 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_category_article_comment_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='artcile',
            new_name='article',
        ),
    ]
