# Generated by Django 5.1.7 on 2025-03-31 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_rename_artcile_comment_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='article_images/'),
        ),
    ]
